### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by drmaize** [KrishnaswamyLab/phateR#14]
Recent updates to phateR seem to have broken functionality...

I had a prior version?? of phateR working, but not for precomputed distance matrices. I noticed recent code updates that might have fixed that, and in order to try it out I installed the new version, but the phate command no longer works.

phateR package installation and in R and loading the library was successful -- sessionInfo shows phateR_0.2.7

However, the phate command with my data or the example data gives the following error

>phate(tree.data$data)
Error in value[[3L]](cond) : 
  Cannot install PHATE, please install through pip (e.g. pip install phate).

**Comment by scottgigante** [comment]
Hi @drmaize, thanks for getting in touch. As a bit of background, we have recently changed the phateR backend to run through the python package as this is much faster - however, it does require that you have the python package installed.

The first check would be to see if the python phate package is installed. You can do this by running a terminal and typing 

```
pip install --user phate
```

Then restart R and try running phateR again. If that doesn't solve the problem, it's possible that phateR is complaining about the installation of phate in Python when in reality the problem lies in another Python package. You can check this by running python from a terminal and typing 

```
import phate
```

If that throws an error, please post it here and I will investigate.

**Comment by drmaize** [comment]
Got it. It's working now. Thank you.

Note: On MacOS, although pip is said to be included in python >3.4 (I installed 3.6.5), I needed to install pip separately using get-pip.py described here: https://pip.pypa.io/en/stable/installing/.

**Comment by scottgigante** [comment]
You're welcome! Thanks for that note - I'll include it in the README in future versions in case others have the same problem.
