### ISSUE TITLE
Why does PHATE not follow standard practice for structuring gene count matrices?

### ISSUE THREAD

**Issue by moldach** [KrishnaswamyLab/phateR#44]
For RNA-seq and scRNA-seq the standard practice is to structure gene count matrix where `rows=genes` and `columns=cells`. 

I'm wondering why PHATE doesn't adhere to this? 

For example, the Seurat package organizes data this way and your competitors except data this way. However, for PHATE one needs to be careful to `transpose()` the data otherwise (which creates an additional cognitive burden for the user):

Comparing a Seurat object called `dataSet` this is how `UMAP` and `FIt-SNE` work in `R`:
 
```
library(bench)

bench_results <- bench::mark(
  uwot <- uwot::umap(dataSet@assays$RNA@scale.data),
  FIt_SNE <- fftRtsne(dataSet@assays$RNA@scale.data),
  phateR <- phateR::phate(t(dataSet@assays$RNA@scale.data))
)
```

![image](https://user-images.githubusercontent.com/5749465/73215076-6310e800-4121-11ea-9fa4-e5a95fa9577d.png)

**Comment by scottgigante** [comment]
PHATE is designed for dimensionality reduction of any kind of data and as such follows standard practice in the data analysis community, wherein rows of a matrix are samples / observations and columns of the matrix are features / dimensions.

You will notice that PCA, tSNE and UMAP all follow the same convention.

```
> X <- phateR::tree.data.small$data
> dim(X)
[1] 250  50
> 
> X_pca <- stats::prcomp(X, rank. = 2)$x
> X_fast_pca <- rsvd::rpca(X, k=2)$x
> X_fast_pca2 <- irlba::prcomp_irlba(X, n=2)$x
> X_tsne <- Rtsne::Rtsne(X)$Y
> X_umap <- umap::umap(X)$layout
> X_uwot <- uwot::umap(X)
> X_phate <- phateR::phate(X)$embedding
> 
> # https://github.com/KlugerLab/FIt-SNE
> source("~/soft/FIt-SNE/fast_tsne.R")
> X_fast_tsne <- fftRtsne(X, fast_tsne_path="~/soft/FIt-SNE/bin/fast_tsne")
> 
> dim(X_pca)
[1] 250   2
> dim(X_fast_pca)
[1] 250   2
> dim(X_fast_pca2)
[1] 250   2
> dim(X_tsne)
[1] 250   2
> dim(X_fast_tsne)
[1] 250   2
> dim(X_umap)
[1] 250   2
> dim(X_uwot)
[1] 250   2
> dim(X_phate)
[1] 250   2
```

Perhaps we should be asking ourselves why Seurat stores its data transposed :)

**Comment by dburkhardt** [comment]
I don't have any historical evidence, but I think the reason that genomics got stuck in the transposed "genes are rows" mindset comes from the fact that genomes often comprise billions of positions. If you want to know the intensity of a ChIP-seq signal at every position in the genome, it's much more convenient to have genes on the rows. This is the convention for BED format, for example.

When bulk-RNA-seq came around, it was still more convenient to have genes on the rows and conditions or samples on the columns, because it was rare for people to have more than a dozen samples and almost unheard of to have more than a couple hundred.

With single-cell, the bioinformatics community in R continued with the convention established by BED / bulk RNA data. However, now that the number of samples is meeting and often surpassing the number of features, we need methods being developed in the data mining / machine learning communities where samples on rows and features on columns has been standard for a long while.
